### ISSUE TITLE
_calcItemPositions should use Math.floor() instead of Math.round()

### ISSUE THREAD

**Issue by slavap** [giotiskl/filterizr#33]
cols = Math.round(self.width() / self.find('.filtr-item').outerWidth());

For example if container is 1024px, and tiles are 400px, cols will be calculated as 3, and as result the last tile in row will be only partially visible. In many cases this behavior is not desired, and can be fixed by using Math.floor(). So ideally there should be an option to control this behavior.

**Comment by giotiskl** [comment]
@slavap this is being fixed by a pull request i will soon merge into the project and will be in the next patch which is shortly coming, so hold tight

**Comment by slavap** [comment]
Sorry, I see PR for fixing this. But IMO it should be an option, in some cases it could be ok to show last tile in row partially (not by default of course).

**Comment by giotiskl** [comment]
I might consider adjusting the PR to make this optional, I'll give it some though during the weekend

**Comment by slavap** [comment]
Thanks! I really like your component.

**Comment by slavap** [comment]
@giotiskl Still not fixed :-( Have you decided to leave this problem "as is" ?

**Comment by giotiskl** [comment]
@slavap this will be made an option as suggested by you, the initial idea was that relative percentage widths should be used for the grid amounting up to 100%. Nevertheless, it is something that I could now work on given that the major rewrite of the core was finished in 1.3.0 which was of higher importance.

**Comment by slavap** [comment]
@giotiskl Thanks! It would be really nice to have it fixed somehow.

**Comment by slavap** [comment]
@giotiskl Found one more problem in FilterContainer.calcColumns(). It should be protected against NaN case, because sometimes when filterizr is not visible on screen, but browser window is resized, I'm getting error "RangeError: Invalid array length". To fix it calcColumns() has to be like this:
```js
calcColumns() {
    var v = Math.round(this.props.w / this.props.FilterItems[0].props.w); // Math.floor() should be here as well!
    return isNaN(v) ? 0 : v;
} 
```

**Comment by giotiskl** [comment]
Post v2.2.0 the logic has been altered to use `Math.floor`.
